webhook 10
mingshewhe/mr_test pull request #5
Opened 2020-08-08 09:34 UTC by iccengan

2020-08-08 09:37 UTC, mingshewhe reviewed
测试评论

2020-08-08 09:40 UTC, mingshewhe approved these changes

2020-08-08 09:40 UTC, mingshewhe requested changes
不通过

2020-08-08 09:41 UTC, mingshewhe reviewed
测试评论webhook

2020-08-08 09:42 UTC, mingshewhe reviewed
测试评论webhook2

2020-08-08 09:44 UTC, mingshewhe approved these changes

2020-08-08 09:46 UTC, mingshewhe reviewed
测试评论webhook3

2020-08-08 09:46 UTC, mingshewhe approved these changes

2020-08-08 09:47 UTC, mingshewhe approved these changes

2020-08-08 10:04 UTC, mingshewhe reviewed
测试评审webhook3

2020-08-08 10:08 UTC, mingshewhe requested changes
测试不通过webhook

2020-08-10 10:30 UTC, mingshewhe reviewed
测试评论2

2020-08-10 10:31 UTC, mingshewhe reviewed
测试评论3

2021-03-16 09:50 UTC, iccengan commented
test

2021-06-10 01:49 UTC, closed without merging